name: Release

on:
  push:
    branches:
      - master
      - beta
jobs:
  release:
    name: Release
    if: github.repository == 'jakowenko/phrame'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i --no-save semantic-release @semantic-release/changelog @semantic-release/exec @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_PAT }}
          GIT_AUTHOR_NAME: David Jakowenko
          GIT_AUTHOR_EMAIL: ${{ secrets.SEMANTIC_RELEASE_EMAIL }}
          GIT_COMMITTER_NAME: David Jakowenko
          GIT_COMMITTER_EMAIL: ${{ secrets.SEMANTIC_RELEASE_EMAIL }}
        run: npx semantic-release
